### ISSUE TITLE
Close right side panels with a mouse click outside their bodies

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1020]
## Purpose

No need to specifically press buttons which open them in order to close them.

E.g. when turning boxed layout off the panel jumps to the right border of the screen, in this case left mouse click outside its body will close it and there will be no need to press the button which closes it.

Panel with flags already auto closes when changing language.

**Comment by Botan626** [comment]
This panel could use the same feature as well.
![image](https://user-images.githubusercontent.com/28785698/86488682-86902c80-bd6a-11ea-8d77-afae5545e0f0.png)

**Comment by MrBurrBurr** [comment]
@Aareksio Any hints on how to solve this properly?

**Comment by Aareksio** [comment]
From our Discord chat:

```js
onWindowClick ($e) {
  const path = $e.path || $e.composedPath()
  if (path.includes(this.$el)) return
  this.active = false
}
```

[Can I use?](https://caniuse.com/#feat=mdn-api_event_composedpath) Yes, you can. `$e.path` is available in Chrome, but not available in other browsers, where we need to call the function.

I'm not sure how well `path.includes(this.$el)`, since path is a list of Nodes, but it works well in Firefox and Chrome - it's possible some less popular browsers (Safari, Brave-thing) may require workaround, but the code above should fail without much havoc.

**Comment by Botan626** [comment]
This panel will close with a mouse click right after 'Theme' word.
![image](https://user-images.githubusercontent.com/28785698/89426918-552cc700-d743-11ea-91f5-16b9fa4e0de8.png)

**Comment by MrBurrBurr** [comment]
> This panel will close with a mouse click right after 'Theme' word, or in any empty space.

Please create a new issue for this.
