### ISSUE TITLE
Don't save same command to history

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#109]
Don't save the last entered command to history if it was the same as the last saved one.

Lets say you enter the following commands in the terminal:

```
A
B
A
A
B
C
A
B
B
C
```

Now the history should only contain the following:

```
A
B
A
B
C
A
B
C
```

**Comment by JustArchi** [comment]
The proper way to go is to implement commands history as unique LRU commands list with fixed history size, as it'd one in every, even the most basic shell.

Just getting rid of duplicates will not make this:

```
A
B
C
B
C
B
B
B
```

Into this history:

```
B
C
A
```

And this is the history that every user would expect, going from `B` into `C` only to go back to `B` again isn't appropriate.

**Comment by Aareksio** [comment]
It's up to the preference I guess. May be good idea to change as keeping copies in history doesn't bring much benefits.

@JustArchi This is not true.

I tested CMD, PS, PuTTY (linux bash) and Git Bash (for Windows) and **none** of them works in LRU manner.

CMD and PuTTY works as @MrBurrBurr described, while PS and Git Bash works as the current ASF-ui implementation.

Please get your facts straight before commenting such bs, or at the very least, do not use sentences as `as it is done in every, even the most basic shell`

**Comment by JustArchi** [comment]
@Aareksio Every shell history uses LRU list, the only difference is that it's not unique. I apologize, I should've used "as it **should** be done in almost every shell", because I see no reason why user should be mashing through 10 same commands just to get to the 11th, clearly he doesn't want to execute the same command on position 8th if he got it at 1st as well.

**Comment by Aareksio** [comment]
This is exactly what @MrBurrBurr suggested and what's been implemented in 81bfa12b737af5d13f3b1f40ac48e577bbcb38dc.

Whether it should work like this is a preference - as we can clearly notice from different implementations in popular shells.

**Comment by JustArchi** [comment]
I'm pretty sure you didn't implement it as LRU set.

```
A
A
A
B
B
B
C
C
C
```

Should still give:

```
C
B
A
```

And not:

```
C
B
B
B
A
A
A
```

It is a preference but I don't see any practical use case when you'd want to smash button through all duplicates to get to what you want to.

**Comment by Aareksio** [comment]
> I'm pretty sure you didn't implement it as LRU set

Indeed, because **it doesns't make sense** to implement this way.
It's currently implemented as something you could call *non-unique LRU* (since LRU's primary feature is uniqueness of its keys, calling it *non-unique LRU* makes no sense).
```
A
B
C
A
C
C
C
```
Becomes (as implemented)
```
C
A
C
B
A
```
Instead of (LRU)
```
C
A
B
```

Which, again, is **exactly** what OP suggested, what CMD and bash shell does. What everyone, including you expect. And it is **not** LRU.

> If anything, current behaviour is the most impractical since it's neither LRU set, nor just a commands history as done in bash shell.

- Current (after the change) behavior is not LRU, instead it works as bash shell and CMD.
- Previous (what you seemingly refer to as *current*) implementation worked as PS or Git Bash for Windows. Since two independent shells work this way, it likely makes sense in certain conditions. Dispute them if you think differently.

**Comment by JustArchi** [comment]
> Current (after the change) behavior is not LRU, instead it works as bash shell and CMD.

Bash works as a simple history list, it doesn't remove duplicates from the last command. Powershell implements **full LRU**, you implemented something that is **neither bash NOR powershell**, **please get your facts straight before commenting such bs**.

```
A
B
C
B
B
```

In bash:

```
B
B
C
B
A
```

In powershell:

```
B
C
A
```

**Comment by Aareksio** [comment]
Then PS is different than yours
![PS screen](https://yko.im/hMMg.png)

Funny enough, my bash is different than yours as well
![bash screen](https://yko.im/8Go7.png)

And guess what, the PS version is what we had, the bash version is what we currently have.

**Comment by JustArchi** [comment]
**HISTORY COMMAND IS NOT THE BEHAVIOUR OF ARROW-UP**.

Seriously.

**Comment by JustArchi** [comment]
Unless you're implementing history of the commands, then you should do it bash way **without** removing last command as a duplicate, since history is not affected by repeated occurances. I thought that this is part of arrow-up history of commands, but if by any chance this is not used as arrow-up but some list of commands that were executed, then it should be done as a simple history list with no changes to it (you do not alter the history).

**Comment by Aareksio** [comment]
**IT HAPPENS TO BE.**

[Seriously](https://yko.im/QeVO.mp4)

**Comment by Aareksio** [comment]
> Unless you're implementing history of the commands, then you should do it bash way without removing last command as a duplicate, since history is not affected by repeated occurances.

It also happens to be.

**Comment by JustArchi** [comment]
Then this should be done as two independent mechanisms:

a) History of commands for archival purposes, where you go full bash way and you do not alter it in any way (do not remove duplicates, duplicates are part of history)
b) History of commands for arrow-up easy access purposes, where you implement full LRU of the list above.

**Comment by Aareksio** [comment]
**It currently works the same way as bash shell.** As demonstrated above.

If you think it should work differently, eg. via implementing LRU, you are free to fork. 

[Good day sir!](https://www.youtube.com/watch?v=HaoySOGlZ_U)

**Comment by JustArchi** [comment]
Bash doesn't remove duplicates from the history, and arrow-up goes strictly as history says, with repeating the same command each time you hit arrow-up, accordingly to occurance, at least in my shell version pointed above. I doubt it changed between bash 4.3 and 4.4, but even if it did, newer version is more appropriate.

**Comment by Aareksio** [comment]
I just tested 4.4 and indeed it changed the behavior:
![Bash 4.4](https://yko.im/5IU-.png)

Anyway, this was the **previous** implementation for ASF-ui, which this issue voiced to **change**. Both implementation (current and previous) are correct and followed the standard set by one of leading shells as I described above, **none of them implements LRU**:

> - Current behavior works as Bash 4.3 and CMD.
> - Previous implementation worked as Bash 4.4 and PS.

The _old_ (CMD, Bash 4.3) implementation was chosen by the community.

**Comment by JustArchi** [comment]
> Previous implementation worked as Bash 4.4 and PS.

If anything, as **your** PS version, since mine (newer) implements full LRU 🙂.

Also I wouldn't consider voice of one user to be what "was chosen by the community", because **this** is what you call a preference, while the most logical choice is to stick with convention used either by bash or powershell - and current version of ASF-ui implements neither.

**Comment by Aareksio** [comment]
Umm...

> - Current behavior works as Bash 4.3 and CMD 10.
> - Previous implementation worked as Bash 4.4 and PS 5.1.17134.228.

The bash 4.4+ way pose some inconveniences for the users, as described in the issue, that's why it was changed to _old_ behavior of bash 4.3.

If your PS implements full LRU, good for you. I don't see a point, as it introduces nothing more than additional inconveniences.

If you want, send a PR implementing a switch between these behaviors, as these differ by single line only. LRU is out of question.

**Comment by JustArchi** [comment]
I don't want anything, I just wonder why you consider LRU (which removes all unnecessary duplicates) less convenient than your current implementation, if at the same time you consider getting rid of just **last** duplicates as convenient. This sounds utterly hypocritical to me, but it's fine.

**Comment by JustArchi** [comment]
Could you tell me in which situation user wants to see `A` again when going arrow-up from `A B C D E F G A H I`? I already saw it when I hit arrow-up for the 3rd time, and it wasn't what I meant, so **why A on 10th arrow-up would be the one I meant**? If I'm looking for `Z` that is on the 11th spot then less arrow-ups for user is **more convenient**, and it has nothing to do with memory efficiency or computing.

You first and foremost define wanted behaviour, and only then pick appropriate data structures to make it happen - LRU is not the data structure here, it is **what the user wants to see**, and yes this is based on latest version of PS - what I consider that PS does better than bash.

Likewise, if I want to see **exact history** of my commands, then I do want to know that I executed `B` 8 times in a row in `A B B B B B B B B C`, something your structure doesn't offer either.

So I'm asking once again, what are you trying to achieve, because it's neither convenience of arrow-up for the user, nor chronological and exact history of commands. If your motivation is "I found this behaviour in bash 4.3 and I like it better" then at least claim so instead of trying to back up your taste by logic that simply doesn't apply.

**Comment by Aareksio** [comment]
- I found this behaviour in bash 4.3 and I like it better
- I explicitly disliked the behavior of LRU implementation, as it was not natural
- This was requested

> what are you trying to achieve

Prove that what you said about LRU being implemented in all, even the most basic shells is bullshit and the implementation choice is a preference, which [I clearly stated at the very beginning](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436248314):

> Please get your facts straight before commenting such bs, or at the very least, do not use sentences as `as it is done in every, even the most basic shell`

After this, I only [repeated](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436320917), [explained why I've choosen such implementation over LRU](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436338058), [proven _my_ bash and PS works differently, and explained how current implementation follows one of these standards, while previous followed another](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436350428), repelled some bullshit [here](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436351351) and [there](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436351678), [repeated that current behavior is one of bash 4.3](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436352930), [confirmed bash 4.3 is different than bash 4.4 and proven none of them implements LRU](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436365015), finally [stated that LRU seems inconvinient to me](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436371204) and expllained why [here](https://github.com/JustArchiNET/ASF-ui/issues/109#issuecomment-436378049).

Right now I am admitting LRU is not landing in because of **my personal dislike**, as if I didn't state that it's a matter of preference `n` comments ago.

**Comment by JustArchi** [comment]
> Right now I am admitting LRU is not landing in because of my personal dislike

Then at least don't claim that it's what everybody would expect 🤔

> What everyone, including you expect. And it is not LRU.

Because I can clearly say that most of the people dealing with any kind of command-line expect bash 4.4+ behaviour, then bash 4.3, then PS. In terms of convenience it goes exact opposite way (PS, then bash 4.3, then bash 4.4) and current ASF-ui is neither convenient (PS) nor expected (bash 4.4), it's exactly in the middle (as bash 4.3).
