### ISSUE TITLE
Implement new API enpoint `/Api/ASF/Encrypt`

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#1095]
Background: https://github.com/JustArchiNET/ArchiSteamFarm/issues/1950#issuecomment-687589692

**Comment by JustArchi** [comment]
There is also /Api/ASF/Hash now (for `IPCPassword`).

**Comment by MrBurrBurr** [comment]
I will close this issue for now since I have no idea how I could implement this UX-wise.

**Comment by JustArchi** [comment]
Idea for implementation @MrBurrBurr

Some key icon next to selected configuration properties you know that support encryption (hard-coded props). Opens a small popup upon clicking.

On screen let user pick from supported `PasswordFormat` and give him textfield, textfield should have that eye icon changing between visible and invisible (stars redacted) password. A button sends API request, fetches the response and automatically puts in appropriate field AND changes `PasswordFormat` to match what user selected in popup.

I think something like that would be neat.

Feel free to close if you disagree or still don't have a good idea.

**Comment by JustArchi** [comment]
^ The same cane be used for `IPCPassword`, just different API endpoint and button saying `Hash` instead. Plus different methods obviously.

**Comment by Abrynos** [comment]
> eye icon changing between visible and invisible

I hope visible being only a valid state, while the users presses down on the mouse-button and it will switch to invisible again, when the mouse-button is released 😉

This will also require hardcoding some values, but it might be one of the few instances where that's a non-bad (not to say "good") idea.

**Comment by JustArchi** [comment]
We should not put it in swagger because it's not standarized in any way, there is no generic mechanism that applies encryption and hashing, I believe ASF-ui should do the very simple hardcoded logic for that:

If exists in global config as a valid property (is defined in schema): `IPCPassword` and `IPCPasswordFormat`, enable hashing for `IPCPassword` based on formats available in `IPCPasswordFormat`.

If exists in bot config as a valid property (is defined in schema): `SteamPassword` and `PasswordFormat`, enable encryption for `SteamPassword` based on formats available in `PasswordFormat`.

If the props disappear or get renamed in the future (very VERY unlikely), the feature will simply stop showing up until somebody corrects it.
