### ISSUE TITLE
Updated interface

### ISSUE THREAD

**Issue by DraikKin** [JustArchiNET/ASF-ui#111]
I don’t write in English, so I use google translate. Some of the functions of the new interface are very convenient, I’m talking about setting up and adding a new bot, but the other part is not convenient. Here are a couple of points:

1. Command bar My asf is on the server and I enter the panel through the telephone. Accordingly, the keys also enter through the phone. Previously, under the black window was a line with a choice of commands, bots and where to enter the keys. Now, one big black window, no reminders by commands, the name of the bot to print for a long time, and most importantly, with a long tap on the screen, the context menu for inserting the key does not come out! You have to either manually type or enter the Steam chat. Then the meaning of the window with the team? Please return the bottom window with a selection of commands, bots and the ability to insert keys.

2. In the window with the bots, it is not clear why the windows with the timer (showing how much was left to farm) and the window with the remaining number of cards were removed. Now, only according to the magazine, you can navigate how many games will still be farming, and it is not clear how long it will take. Calculating yourself is not very convenient if the farm has more than 20 games. Please return these timers

**Comment by MrBurrBurr** [comment]
1. So as far as I understand you there are multiple problems:
- `no reminders by commands`
  _Use "commands" for a list of all available commands and "help <Command>" for a little description what the command does._
- "the name of the bot to print for a long time"
  _I don't know what you mean by that._
- "with a long tap on the screen, the context menu for inserting the key does not come out"
  _This issue was already reported [here](https://github.com/JustArchiNET/ASF-ui/issues/94)._

2. Farming info did already get implemented ([Commit](https://github.com/JustArchiNET/ASF-ui/commit/9f63bd05fd8536cf5b279ba4e73a6700d3a24938))

**Comment by Aareksio** [comment]
What do you want to achieve?

From the description I assume you want to `redeem` a key on a bot, correct?

**Comment by Aareksio** [comment]
I have tested on the phone and the problem seems to be lack of command autocompletion. The problem with phone input is that it's treated with [IME](https://en.wikipedia.org/wiki/Input_method), therefore we do not know its value until the word is complete. Supporting IME, while partially possible, is currently not planned.

`Commands` view is not meant be used by end users. We should implement whatever action is needed to `Bots` interface instead.

**Comment by Botan626** [comment]
@MrBurrBurr 

I read his closed issue in rus and I will translate the 1st part of it:

1. The Commands window. My ASF runs on a server and I use my mobile phone for ASF UI. And I enter my keys via mobile phone as well. Previous ASF UI version had the ability to choose a command via a drop up menu, as well the ability to choose a bot and it had an extra field for entering the keys. **NOW** it's only one big overall window, no reminders for commands, it takes long time to print bot's name, also there is no option to paste the text (key) when tap and hold the screen. So I either input the key manually or I use Steam's chat. What's the point for Commands window then? Please get back the lower instruments for choosing commands, bots and entering the keys.

**Comment by Aareksio** [comment]
Thanks for translations. Seems like my previous understanding was correct.

Since we cannot easily impllement IME and the functionality should be accessible from _clicky_ interface anyway, we should implement whatever is needed in `Bots` tab.

Current solution is to use BGR instead of `Commands` tab.

@MrBurrBurr Could you please confirm my understanding, close this issue and open new one, with proper name and description?
