### ISSUE TITLE
Make all links work in Changelog

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1325]
This is a changelog on GitHub, there are 5 links, text colored blue:

![image](https://user-images.githubusercontent.com/28785698/110676285-d8842e80-81e4-11eb-9486-1411db7c1c4c.png)

This is a changelog in ASF-ui, 3 links are missing:

![image](https://user-images.githubusercontent.com/28785698/110676684-49c3e180-81e5-11eb-979f-c45ff25e6ca6.png)

**Comment by MrBurrBurr** [comment]
After taking a quick look I am not too sure if we want to implement this.

The 'missing' links are in fact not missing. The api returns them as a text and ASF-ui displays them correctly as text.

You will see that those texts are links on the github page. This is because github will turn it into a link if it detects its own domain. Same for the "#2219", github will link it to the issue with that number.

We _could_ implement something that works the same but this will be very prune to failing and also a hassle to maintain for no real advantage.

I would like to hear @Aareksio or @JustArchi opinion.

**Comment by JustArchi** [comment]
We don't want to do stuff like `#2219` because it's in fact not a link, and as you said, this is GitHub doing its own thing.

However, as you can see from screenshot above, there is a full link starting with `https://` above, and almost all, even very limited editors, automatically detect the link and make it clickable, even if user didn't intend it to. You can see this by posting a totally random link even here, such as https://steamcommunity.com/groups/archiasf - GitHub will make it a hyperlink by default, you'd actually need to put it in `code` to avoid that happening.

So yes, that alone is something worth consideration, but no, GitHub-specific stuff like `#2219` we shouldn't bother with.

**Comment by MrBurrBurr** [comment]
So we should detect strings starting with:
- `http://`
- `https://`
- `www.`

Did I forget something?

**Comment by JustArchi** [comment]
Don't reinvent the wheel, use something like https://www.npmjs.com/package/linkifyjs

**Comment by Botan626** [comment]
> MrBurrBurr closed this in 880a584 2 hours ago

I had to clear local storage to make this commit work, CTRL+F5 didn't do it.

![image](https://user-images.githubusercontent.com/28785698/110855035-e14d3100-82c6-11eb-9a1c-a8f137df653f.png)

**Comment by Abrynos** [comment]
@Botan626 Because changelog is cached in localstorage.

@MrBurrBurr Do I remember wrong or do we actually have logic to detect UI update. If yes: Would it be a good idea to invalidate caches at that point as well?

**Comment by Botan626** [comment]
> We don't want to do stuff like `#2219` because it's in fact not a link, and as you said, this is GitHub doing its own thing.
> So yes, that alone is something worth consideration, but no, GitHub-specific stuff like `#2219` we shouldn't bother with.

> You will see that those texts are links on the github page. This is because github will turn it into a link if it detects its own domain. Same for the "#2219", github will link it to the issue with that number.

ASF-ui handles release tag links like "V5.0.4.3", or whatever it is if not a link, why can't it do the same for "#2219"?

**Comment by MrBurrBurr** [comment]
@Abrynos This is a great idea, but currently we do not detect if a UI update has happened. But in theory this should be fairly easy to implement.

@Botan626 The version-tag is already inside an "a"-tag when ASF-ui receives the response from api.
