### ISSUE TITLE
Introduce ASF-ui wiki

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#1429]
We could get rid of FEATURES.md and add a very simple FAQ.

@Botan626 I know you like to write documentation. Feel free to suggest your ideas for a wiki when you have time.

**Comment by MrBurrBurr** [comment]
I created a very basic wiki. This should do for now.

**Comment by Botan626** [comment]
1. I guess what you created can be roughly called wiki, because it tells how to use ASF-ui, but I see wikis more as a place of a complete documentation.

You already have 'How to use' section on repo's front page, I'd put all info in there.

2. 'If you are unsure about how to setup ASF-ui you can read more about it on ASF's wiki.' --- I don't see Setup section in the wiki and, as far as I'm aware, there is no need to setup UI.

3. Buttons in the footer. I have no idea, why you keeping `Discussions` there, could you explain why?

And now `Wiki` button opens UI's wiki, I totally dislike this, I want this button to open ASF wiki.

**Comment by Botan626** [comment]
I also don't like this FAQ, created to answer this one question. This way UI developers tell themselves they know about a major technical flaw, which doesn't allow to simply use ASF-ui after ASF update.
