### ISSUE TITLE
Implement new API enpoint `/Api/Storage`

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#1431]
Related: https://github.com/JustArchiNET/ArchiSteamFarm/issues/2337
https://discord.com/channels/267292556709068800/332735075315744768/855553458781290517

**Comment by JustArchi** [comment]
Remember that each key should be prefixed with some unique identifier, like `asfui-`. I'm just highlighting that fact because ASF-ui can't expect to be the only consumer of this, and we don't want 2+ tools to clash over something common like `settings` or `cache`.

Saving stuff under e.g. `asfui-settings` sounds bulletproof enough for me.
