### ISSUE TITLE
ASF-ui doesn't redirect to Setup page after ASF update

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1434]
## Steps to reproduce

1. Press on Install badge on Releases page,
2. Click on 'Trying to update...' notification, 
3. Wait for 100% download,
4. See screenshot.

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/122822848-4ad9d400-d2e7-11eb-8afe-2187e0f16ce4.png)

</details> 

## Additional information
UI was version [3889280](https://github.com/JustArchiNET/ASF-ui/actions/runs/953569267), UI was located in TargetDirectory, ASF was running with `--path <path>` command-line argument.

**Comment by MrBurrBurr** [comment]
This happens for the same reason as explained in #1423. I will close this issue since it is a duplicate.

**Comment by Aareksio** [comment]
Once we request update and ASF confirms it is updating, we can request ASF version in loop. Once the version changes, we shall issue page reload (`window.location.reload()`)

**Comment by Aareksio** [comment]
It seems this is already implemented, but since the update endpoint never returns, we redirect to wait page once ASF is already restarting. This can be solved by returning HTTP 204 from POST /api/asf/update.

I am positive we should add page reload once ASF is back online after update, to fetch new asf-ui files.

**Comment by MrBurrBurr** [comment]
This was fixed with https://github.com/JustArchiNET/ASF-ui/commit/aed6536b3b854db72a10ad66455efd856b426ed3
