### ISSUE TITLE
Speed up editing flag configuration properties

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#1449]
## Purpose
Speed up workflow for the user when editing flag-enum configuration properties

## Solution
Instead of having to click the `Add` button every time I want to add a value to a *flag enum* (e.g. for the config property `BotBehaviour`) I have to press the add-button. I'd like the value to be automatically added when selecting it from the dropdown.

## Alternatives
Do nothing and leave it at two clicks necessary for each value.

**Comment by Botan626** [comment]
This issue could be combined with #1442 and dropdown menu could have such structure:
![image](https://user-images.githubusercontent.com/28785698/123232606-fc445980-d4e1-11eb-9547-8df37804d822.png)

Instead of 'Every day' it could have `All` option and instead of 'Last Weekday in month' it could have `None` option. And property values instead of days of course. No need for `Add` button then.
