### ISSUE TITLE
Highlight focused values in dropdown menus with UI's theme color

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1452]
Currently UI highlights values in focus with blue color only, regardless what theme color is.

![image](https://user-images.githubusercontent.com/28785698/123702462-d7e2d700-d86b-11eb-9f77-5db3efb8dc45.png)

**Comment by MrBurrBurr** [comment]
Feel free to read [this article](https://css-tricks.com/the-current-state-of-styling-selects-in-2019/) if you want to understand why it's blue.

If we do not want to wait for browser devs to add styling support for option elements we would have to rewrite all select elements to be list elements and then do a little bit of our own magic on top.

I think this is a lot to change just for the color to be different, that's why I added it as PR-ok and Wishlist.

**Comment by MrBurrBurr** [comment]
After rethinking a bit I changed my mind and will close this issue for now.

The reason is that it's a small enhancement for the user, but a lot to change for a dev.

If someone wants so create a PR that implements either one of my suggestions I will gladly accept it.
Until then this issue will stay closed.
