### ISSUE TITLE
Allow multiple values selection in dropdown menus

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1456]
## Purpose
To have a possibility to select multiple values in the dropdown menu, until it's closed with an outside mouse click.

**Comment by Abrynos** [comment]
As I previously layed out in my merge request [over here](https://github.com/JustArchiNET/ASF-ui/pull/1450): I am not a fan of this idea.

**Comment by Botan626** [comment]
> As I previously layed out in my merge request [over here](https://github.com/JustArchiNET/ASF-ui/pull/1450): I am not a fan of this idea.

You said multiple times, that it's hard for you to implement. You never gave a real reason, why you don't like this idea itself.

**Comment by Abrynos** [comment]
> [...] get [this idea] working with `InputList` where the order of selection matters [...], _without_ having two (or rather three) _extremely_ similar types of input being displayed in two completely different ways.

Why would we display them differently? Because if we leave the dropdown open it hides the items below the dropdown menu, which is how the user can see in which order the selected values are.

Additionally I cannot see a way of keeping our current "None" option, which in my opinion is rather important. This is a classic case of one "checkmark" in a selection changing the state of another "checkmark", which is something you usually want to avoid.

There is also the problem of clicking on the "background". Currently we close the whole modal when doing that.

And the most important thing to keep in mind is **_simplicity_**. You want any GUI to be as simple as possible for the user. A plain dropdown menu is simple. A dropdown menu with checkboxes inside is not (in comparison). In that case we could just make the whole thing checkboxes in the first place and remove the dropdown and "badges" below it completely. (I am against that as well, because it makes the whole thing much bigger, clutters your screen and you'll have more scrolling to do to find the config property you are searching for 😉)

**Comment by Botan626** [comment]
> Why would we display them differently? Because if we leave the dropdown open it hides the items below the dropdown menu, which is how the user can see in which order the selected values are.

1st, I have no idea what you are quoting. I read this part and stopped reading. This already had answer in this comment https://github.com/JustArchiNET/ASF-ui/pull/1450#issuecomment-870025328

> I just had another idea. The dropdown menu could be without checkboxes, but it could allow to multi select property values, until it's closed. Selected values could be highlighted with ui's theme color, and focused values could be highlighted with pale grey color.

Should I continue reading, or maybe you want to rethink your comment and edit it?

**Comment by Botan626** [comment]
> > [...] get [this idea] working with `InputList` where the order of selection matters [...], _without_ having two (or rather three) _extremely_ similar types of input being displayed in two completely different ways.
> 
> Why would we display them differently? Because if we leave the dropdown open it hides the items below the dropdown menu, which is how the user can see in which order the selected values are.
> 
> Additionally I cannot see a way of keeping our current "None" option, which in my opinion is rather important. This is a classic case of one "checkmark" in a selection changing the state of another "checkmark", which is something you usually want to avoid.
> 
> There is also the problem of clicking on the "background". Currently we close the whole modal when doing that.
> 
> And the most important thing to keep in mind is **_simplicity_**. You want any GUI to be as simple as possible for the user. A plain dropdown menu is simple. A dropdown menu with checkboxes inside is not (in comparison). In that case we could just make the whole thing checkboxes in the first place and remove the dropdown and "badges" below it completely. (I am against that as well, because it makes the whole thing much bigger, clutters your screen and you'll have more scrolling to do to find the config property you are searching for 😉)

Did you mean to comment for this issue #1458 ?

**Comment by Abrynos** [comment]
> The dropdown menu could be without checkboxes, but it could allow to multi select property values, until it's closed. Selected values could be highlighted with ui's theme color, and focused values could be highlighted with pale grey color.

This is still a dropdown menu with checkboxes. Making it look a bit different won't change that fact.

> Did you mean to comment for this issue

no

**Comment by Abrynos** [comment]
As I said on discord: I am not participating in this discussion any more (at least not responding to your comments).

Other than "it may be convenient" you got nothing to support this suggestion and I have laid out plenty of reasons against it. Accept it or find some more reasons.

**Comment by MrBurrBurr** [comment]
Small enhancement for the user, huge pain in the ass for a dev.

If someone wants so create a PR that takes care of every mentioned concern I will gladly accept it.
Until then this issue will stay closed.

**Comment by Botan626** [comment]
> proof me wrong

No, it's you who has to proof values of your weak reasons. Maybe it's hard to code, I don't know, all other reasons you say here are just irrelevant.

**Comment by Botan626** [comment]
> takes care of every mentioned concern

What every concern? DD menu already hides selected values. Why 'None' option has to go? Backgroung thing I don't get at all.

What about Wishlist label?

**Comment by MrBurrBurr** [comment]
> What every concern? DD menu already hides selected values. Why 'None' option has to go? Backgroung thing I don't get at all.

Abry already explained most of the concern I have about this enhancement. It's really complicated to implement in a way that is maintainable, readable and works. It might seem easy for someone that does not understand how to code. But it is still a valid suggestion, that's why I added the `PR-ok` label and not the `Not going to happen` label.

> What about Wishlist label?

We do not set `Whishlist` label and `No solution yet` label at the same time. No point in doing so.
