### ISSUE TITLE
Latest version does not respect pathbase

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#1467]
## Description
The version bundled with the latest release of ASF tries to load the bundle.js file from `/scripts/main.{hash}.bundle.js` instead of `/{pathBase}/scripts/main.{hash}.bundle.js`.

## Steps to reproduce
- Install latest version of ASF 
- Add custom IPC configuration with `PathBase` option
- Add reverse proxy in front of ASF, making sure that the root directory (in particular `/scripts`) will not be forwarded to ASF
- Access ASF-ui via reverse proxy

## Expected behavior
ASF-ui loads and displays correctly

## Current behavior
ASF-ui fails to load its main bundle due to it being loaded from the root directory.

## Additional information
[example_config_files.zip](https://github.com/JustArchiNET/ASF-ui/files/6758012/example_config_files.zip)

**Comment by Zuko** [comment]
I don't know if this is due to the same error but...

Latest ASF keeps redirecting me to `<domain>/page/PathBase/`

![Zrzut ekranu 2021-07-03 093939](https://user-images.githubusercontent.com/521035/124347346-89736680-dbe4-11eb-8598-cf0b2b0f4720.png)

When I "correct" URL to eg. `<domain>/PathBase/page/bots` 

![Zrzut ekranu 2021-07-03 095646](https://user-images.githubusercontent.com/521035/124347498-609fa100-dbe5-11eb-91bd-9a8dbfa3bd11.png)
