### ISSUE TITLE
invalid currency in asf-ui

### ISSUE THREAD

**Issue by wollframium** [JustArchiNET/ASF-ui#1492]
does not correctly indicate the currency of kazkhstan. writes that the currency is not kakhakhstan, but the Kuwaiti dollar.
I saw this a very long time ago, in winter, but I didn’t want to disturb you because it’s not essential. but I think it's better to fix the bug) suddenly someone will think why my currency has changed and why I have so much money on my account)
![dC6s1s_lvlg](https://user-images.githubusercontent.com/65495044/127764139-f60248de-d09c-4f04-9900-820215308356.jpg)
![Pq2zwzc0f7I](https://user-images.githubusercontent.com/65495044/127764141-53a7ab67-6933-4fc7-84c4-e77361c430a7.jpg)

**Comment by MrBurrBurr** [comment]
Thank you very much for reporting this issue!

I guess Steam updated their list of currencies and since we are not fetching them from swagger yet they are outdated.

> I saw this a very long time ago, in winter, but I didn’t want to disturb you because it’s not essential.

In the future just feel free to report any issues you encounter. Bug reports or new feature ideas are never disturbing.

I will take a look as soon as I have some spare time.

**Comment by JustArchi** [comment]
This is why I told @MrBurrBurr a while ago to never hardcode the list himself but fetch from ASF because it changed, changes right now and will change in the future 😁.

**Comment by MrBurrBurr** [comment]
I just took a quick look and swagger returns the same enums as always.

`"KZT": 37, "KWD": 38,`

Seems like nothing has changed there.

@JustArchi Any idea what could cause this?

**Comment by JustArchi** [comment]
@MrBurrBurr if bot command returns correct currency but ASF-ui returns wrong one then something on your end, because ASF exposes the same underlying enum to you through swagger.

**Comment by MrBurrBurr** [comment]
@wollframium Could you paste the result of `http://localhost:1242/api/bot/BOTNAME?password=IPC_PASSWORD`? That way I can see what value the api is returning for `WalletCurrency`.

**Comment by JustArchi** [comment]
@MrBurrBurr And I see what.

https://github.com/JustArchiNET/ASF-ui/blob/main/src/utils/getCountryCode.js

You're accessing this array by an index, not by identifier, and due to lack of `33` id, you're missing offset by one once you get past through that id further below.

User has `37` (KZT), but your array index for `37` returns `38` (KWD).

**Comment by wollframium** [comment]
> @wollframium Could you paste the result of `http://localhost:1242/api/bot/BOTNAME?password=IPC_PASSWORD`? That way I can see what value the api is returning for `WalletCurrency`.

walletbalance :6473 walletcurency :37

as I understand it, if kzt is 37, then everything is correct according to this link

**Comment by JustArchi** [comment]
Yep, this confirms my suspicion, so it's a display bug in ASF-ui, ASF properly represents this currency to the API consumers.

Thanks 🙂
