### ISSUE TITLE
Can't see log page when use cloudflare in Proxied mode

### ISSUE THREAD

**Issue by cyb233** [JustArchiNET/ASF-ui#1567]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

892742c

### Bug description

when I use host with cloud flarein `Proxied` mode, and enter the log page, it will throw exception: `TypeError: Cannot read properties of undefined (reading 'replace')`, and it will no problem without cloud flare.
![image](https://user-images.githubusercontent.com/39186981/166935507-137270b2-a274-478e-99f0-1c72777543fc.png)
see also: https://github.com/JustArchiNET/ArchiSteamFarm/discussions/2563

it will happen when set cloud flare in `Development Mode`
and solved when  set the host `DNS only`.
![image](https://user-images.githubusercontent.com/39186981/166955632-a2cc67ae-b676-4c9c-aed5-5e916b7a9cff.png)
it's only happen in log page

### Expected behavior

I exprcted that I can see the log, and protect my server by cloud flare.

### Actual behavior

when I protect my server by cloud flare, I can't see any log.

### Steps to reproduce

when use cloud flare to set a DNS Record in `Proxied` mode:
![image](https://user-images.githubusercontent.com/39186981/166955632-a2cc67ae-b676-4c9c-aed5-5e916b7a9cff.png)

### Possible reason/solution

it's only happenned in cloud flare with Proxied, I'm not sure if the problem is cloud flare or the framework.

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

### Additional info

if it can be resolved, I have time to test, and if not, I want know why.

**Comment by cyb233** [comment]
maybe I found why exception: `window.__BASE_URL__` is `undefined`. how to fix it?
![image](https://user-images.githubusercontent.com/39186981/166974779-ce95b469-d2ce-44a7-87e6-ad05de0fda40.png)
left proxied by cf and another not

**Comment by Aareksio** [comment]
The error is pointing to `window.__BASE_URL__` being undefined indeed. This variable is set in 2 places:

- https://github.com/JustArchiNET/ASF-ui/blob/main/src/index.html#L49
- https://github.com/JustArchiNET/ASF-ui/blob/main/src/index.html#L80

Second path is activated when the main scripts fail to load from expected path.
First path is activated when the main script loads from expected path AND it did not fail before.

Either way, I see no way how this code could not be set by the time we attempt to connect websocket.

To give more insight, I need you to verify neither of those paths activated. To do this, please open `www/index.html` and add a `console.log` statements in highlighted places:

![image](https://user-images.githubusercontent.com/11166786/167032927-fbb6a329-6a31-4710-bc63-770595a718c4.png)
![image](https://user-images.githubusercontent.com/11166786/167032974-dca1a96b-10fa-4be4-9540-7f83e4654f44.png)

If none of those happens to fire when CF's proxy is enabled, I'd appriciate if you could show full rendered HTML (right click > View Source > copy whole source). I suspect CloudFlare may be doing some magic behind the scenes which prevents the script from working in predictable manner.

---

My bets what is going on:

1. CloudFlare is using server-push (or early hints) to send the script along with initial document. This leads to `<script src="main.js"/>` being evaluated **before** inline script due to it's higher placement in HTML. I think this may be the case, as given there shouldn't be `async` or `defer` modifiers, browser have no reason to skip evaluating available script right away.

![image](https://user-images.githubusercontent.com/11166786/167033669-f2d29db8-8aef-4c3f-a233-f80715ff5a0d.png)

2. CloudFlare is inlining the `main.js` script, the result is ultimately the same as above, the main script is parsed before inline script mounts load watcher and `onload` is never captured.

![image](https://user-images.githubusercontent.com/11166786/167033807-030c981f-2346-491a-a2d0-37e31114cd0a.png)

(options on screenshots may not represent the actual CF features _at fault_, but you can try turning them off)

**Comment by mrskizzex** [comment]
![image](https://user-images.githubusercontent.com/11503128/167035731-feb26fef-82f2-463a-a526-b6305d29d476.png)
![image](https://user-images.githubusercontent.com/11503128/167035905-3408adf2-fef3-4cca-8389-167d3b13b2d3.png)
I'm going to be unhelpful and say a classic: works for me.

**Comment by cyb233** [comment]
it seems realy caused by `Rocket Loader™`, it works well when I turn off it. thx.

I think it can be added into faq.

**Comment by Aareksio** [comment]
@cyb233 Could you please provide the rendered HTML for reference? I am positive we could adjust our code to work with Rocket Loader :)

**Comment by cyb233** [comment]
> 

with Rocket Loader or without？

**Comment by cyb233** [comment]
souce file:
[index.txt](https://github.com/JustArchiNET/ASF-ui/files/8636685/index.txt)
view-source without Rocket Loader:
[index_view-source_without_RL.txt](https://github.com/JustArchiNET/ASF-ui/files/8636686/index_view-source_without_RL.txt)
view-source with Rocket Loader:(wait)
