### ISSUE TITLE
Average selling price (ASP)

### ISSUE THREAD

**Issue by AllystrevJubate** [JustArchiNET/ASF-ui#1702]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

Purpose is to give new and useful functionality for trading cards payback.

### Solution

Implement function (or create one) in ASF-ui like Steam Tools Trading Cards to see average price of selling all currently farming cards. 

### Why currently available solutions are not sufficient?

Currently there is no sufficient solution.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

### Additional info

it's not a secret that many people use ASF to farm and sell trading cards. This feature could be very useful for them. I don’t know how difficult it is to implement or if it’s worth the effort, but since it has already been done, it’s definitely possible. The attached file contains concepts of how it could look.

![Screenshot 2024-12-08 205009 copy](https://github.com/user-attachments/assets/a9fbffc6-8a9c-4696-b647-c7698c899432)
![Screenshot 2024-12-08 210354 copy](https://github.com/user-attachments/assets/e3f6b153-ee8c-457b-a7de-2dbe7a8a32ac)

**Comment by JustArchi** [comment]
This requires ASF support, as ASF-ui is only frontend to data gathered by ASF.

As of ASF, it's entirely outside of its scope. Moreover, entirely against Steam ToS, which explicitly states steam community market as a marketplace, with any automation towards it as undesired.

You're free to implement ASF plugin for such feature if deemed appropriate, but as of ASF core, it's simply not going to happen, and by extension, since there is no data gathered by ASF, ASF-ui is unlikely to gather it standalon either, due to similar reasons.
