### ISSUE TITLE
Log section empty

### ISSUE THREAD

**Issue by D3XX3R1337** [JustArchiNET/ASF-ui#187]
The log section is completely empty in the ASF-UI.

**Comment by Aareksio** [comment]
After over a week I didn't notice any errors reported regarding this issue. This may be due to reporting tool not catching the error properly or the program simply misbehaving instead of erroring.

If the issue persists, please try looking for the error in network tab of your browser's devtools.

![Network tab, Chrome Devtools](https://yko.im/apQz.png)

**Comment by D3XX3R1337** [comment]
The Status Code of the request is "400 Bad Request"

**Comment by MrBurrBurr** [comment]
Status code 400 means that the request has failed. You should check the message from the response body for the actual reason. Most of the time this is ASF, understanding the request, but refusing to execute it due to provided reason.

**Comment by D3XX3R1337** [comment]
I'm using an Nginx Reverse Proxy.

**Comment by Aareksio** [comment]
This looks like proxy misconfiguration, not ASF or UI issue.

One the last note, I suggest checking "response" tab of this request, it may help you find the cause of the issue.

The setup you use is not recommended and requires additional configuration, which we do not support.
