### ISSUE TITLE
Copy to clipboard not working for 2fa token

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#294]
https://www.w3.org/TR/clipboard-apis/#integration-with-other-scripts-and-events

**Comment by Aareksio** [comment]
Yup, the browser is losing user intent in async event handlers... Once we fetch the token when the modal shows, we can make copying synchronous. Just remember the token expires in about a minute, so we have to update it if the user stays on the page for longer periods.

**Comment by MrBurrBurr** [comment]
Are you sure that the token will expire in about a minute? I remember it being valid for something in the range of 10-30 seconds. We will have to do some research about that.

**Comment by Aareksio** [comment]
The token is generated in 30 seconds intervals, but _most_ implementations, including Steam one, allow for at least one token _lag_, meaning the code can be used in it's own window (0s, 30s), previous token window (-30s, 0s) and the next token window (30s, 60s).

Doesn't matter in our case, we may as well refresh it every 10 seconds, since we don't know the exact _expiry date_
