### ISSUE TITLE
Remove Changelog in footer

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#411]
We have Changelog in the Navigation and GitHub link in the footer, so it's useless.

**Comment by Aareksio** [comment]
I could point out plenty of other features that are _more_ useless (~a list that's better to stay redacted~). The link in footer points to GH releases (which is not the same as ASF-ui changelog tab) and _looks nice_.

Even if it didn't, the duplication is not a reason to remove such thing. Just because you can say pause a bot from the interface, doesn't mean we should remove it from `Commands`, right?

We may do something about it if, and only if there's need for additional space on the footer.

**Comment by Botan626** [comment]
>The link in footer points to GH releases
So it's not Changelog.

>looks nice
Personal opinion.

>we should remove it from `Commands`
No such button on Commands page, the user needs to type command.

**Comment by Botan626** [comment]
>the duplication is not a reason to remove such thing

So we can add more duplicate stuff and you will be ok with it?

**Comment by Aareksio** [comment]
> > The link in footer points to GH releases
> 
> So it's not Changelog per se.

It happens that the changelog is the main part of the release note, but yes, these are different. That said, I find using name `release` to be possibly confusing for general audience.

> > looks nice
> 
> Personal opinion.

Precisely why it's in _italic_ font.

> > we should remove it from `Commands`
> 
> No such button on Commands page, the user needs to type in a command.

But it autocompletes the command. Why would you need that, if you can achieve the same using UI?

> > the duplication is not a reason to remove such thing
> 
> So we can add more duplicate stuff and you will be ok with it?

If the new solution solves it's own problem apart from the already solved one - yes, I see no reason not to.

**Comment by Botan626** [comment]
Implemented in [commit 39db4788be2695ffa30bcaaaaea4b656e7f83ef0](https://github.com/JustArchiNET/ASF-ui/commit/39db4788be2695ffa30bcaaaaea4b656e7f83ef0).
