### ISSUE TITLE
Check `name` property in bot config to cleanup #468

### ISSUE THREAD

**Issue by Aareksio** [JustArchiNET/ASF-ui#536]
We screwed up a bit with #468 by adding `name` property to user's bot configuration.

Should we attempt to revert the change by removing `name` from existing configs on update?

I don't like the idea of screwing with user's configuration without their consent, but the topic is open for discussion.

**Comment by JustArchi** [comment]
The best idea that comes to my mind is checking against `name` property in the bot config and asking user if he wants to regenerate his config by removing that one.

In normal conditions ASF would not even accept `name` from you, but since introduction of plugin system in V4+, ASF both writes and reads custom properties to/from you, in order to preserve them for custom plugins that may make use of them.

**Comment by deluxghost** [comment]
i prefer archi's idea.
an interesting fact, such function looks like a deprecation/migration manager, treat `name` as a deprecated property 🤔

**Comment by MrBurrBurr** [comment]
@Aareksio Do we still want to do a clean up after this much time has passed?

**Comment by Aareksio** [comment]
I don't think it's necessary anymore. Let's close this.
