### ISSUE TITLE
Smooth scrolling on mobile

### ISSUE THREAD

**Issue by Zignixx** [JustArchiNET/ASF-ui#677]
It would be nice to have a smooth scrolling on mobile. Currently it stops when you release the touch. Many other sites have a keep scrolling (and slow down). That would be nice!

**Comment by Aareksio** [comment]
That's weird because this behavior is defined by the browser, not the webpage - at least at the root level of the document. Possibly we use another container for scrollable content, which do not have the _smooth scrolling_ effect enabled by default. Gonna take a look.

We need to be careful with any form of scroll manipulation too, as many users strongly dislike it.

**Comment by Zignixx** [comment]
Ah ok! Maybe a ui setting for it? Disabled by default. So everyone who want to use that can enable it

**Comment by MrBurrBurr** [comment]
> Gonna take a look

@Aareksio did you find any solution or do you want to close this issue?
