### ISSUE TITLE
Redirect to last visited page not working

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#85]
When I navigate to bots page and close the tab, then open a new tab, navigate to `http://ip:port`it wont redirect me to bots page but rather to home page.

**Comment by Aareksio** [comment]
Why exactly would that be the expected behavior?

**Comment by MrBurrBurr** [comment]
I think it could be more convenient for the user.

We had it in the old GUI because someone requested in on discord.

**Comment by JustArchi** [comment]
We had it in the old GUI because there was no way to save any kind of absolute URL as old GUI had only one way to be accessed.

With ASF-ui and proper URL routing, user can just save URL to whatever page he wants as a tab, I see this issue not only as unwanted, but actually **outright harmful** to add in the first place.

**Comment by MrBurrBurr** [comment]
I agree but why would it be "outright harmful"?

**Comment by JustArchi** [comment]
Because if I'm typing `http://127.0.0.1:1242/` in my browser then I want to see `index.html` aka home, and not whatever I visited last time in the UI.

**Comment by JustArchi** [comment]
At the same time I see no reason why this couldn't be an option in the UI (with default turned to off how most of the users expect it to be). The question is just if you consider it worth it to add - I see absolutely no need for that considering arguments I pointed out above.
