### ISSUE TITLE
Review current CIs

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#850]
@JustArchi Does ASF-ui really need all of them? Any chance we can at least get rid of travis?

- GithubCI
- AppVeyor
- Travis
- CircleCI

**Comment by JustArchi** [comment]
Need - no, but I don't see any reason for removing something that is already integrated, works and doesn't cause any problems.

**Comment by MrBurrBurr** [comment]
I get your point and maybe its just me but it seems a little unnecessary to have 2 (3?) CIs doing the exact same thing. To be honest I have little to no knowledge about CIs so thats why I am wondering why you would "clutter" a project in that way. Does one of the CIs each have a benefit over the other and thats why? For example I know that not all CIs provide artifacts so that would be a reason that I can think of. Maybe you could shine some light on my lack of knowledge.

**Comment by JustArchi** [comment]
Testing on more CIs can give you duplication in case of environment problem with just a single service, including temporary downtimes. Having at least 2 different CIs per OS to build for is generally a good idea, and in our case we have barely 4 for Windows and 3 for Linux / OS X, something far too little to be considered "excessive".

Like I said in the previous message, I wouldn't add e.g. Travis if I was making the decision today, since with remaining 3 we're good, but considering it's already set and prepared, there is not a single reason to get rid of it, as it doesn't cause any problem, cost or burden whatsoever for you.

**Comment by JustArchi** [comment]
And neither every single one of the CIs you mentioned is the same. While they serve similar role, they have their own advantages/disadvantages which work without downsides only when combined.

- AppVeyor has excellent GitHub releases automation, something no other CI does, but their non-Windows support is at very early stage and not that much reliable yet.
- Travis has long history of excellent support for Linus and OS X, OS X far earlier than other ones, but their Windows containers are at early stage and not that reliable yet.
- CircleCI is full of issues with open-source plans, it's 3rd week I'm exchanging e-mails with their support and I don't think they actually understand my problem, if they won't do anything with failed builds caused by them, I'll simply get rid of it first since it's entirely unreliable.
- GitHub is at very early stage with the whole workflow concept, and it'll be a long time before it can be considered stable.

When you add everything above, you get the real situation we're in right now, which is **far** from perfect:
- I can trust only AppVeyor to build on Windows
- I can trust only Travis to build on Linux and OS X
- CircleCI is unreliable, GitHub I've added just a few days ago
- Only AppVeyor offers easy publish of GitHub releases

And CircleCI I've added mainly on @Aareksio request.

**Comment by MrBurrBurr** [comment]
Makes sense, thanks for explaining. But one thing I argue against is this:

> as it doesn't cause any problem, cost or burden whatsoever for you.

Travis actually caused some "problems" before because it is so damn slow. Not really a problem, hence the quotation but still its something that bugs me to the point where I opened this issue. 

I hope that in the future GitHubCI will be so good that it can replace at least Travis. But I think you explained everything so well that I can close this issue here. Thanks again for your help.

**Comment by JustArchi** [comment]
Waiting for the CI is not a burden, it gives you time to analyze the PR, and judging by the **[last PR merged by dependabot](https://github.com/JustArchiNET/ASF-ui/pull/851)**, all checks have passed in 5 minutes since the PR, if this is "so damn slow" for you, then I guess you're too impatient for any CI to kick in, since even the fastest ones won't give you time under a few minutes, considering ASF-ui builds for a full minute at the fastest.
