### ISSUE TITLE
Unable to enter 2FA codes in ASF-ui

### ISSUE THREAD

**Issue by ghost** [JustArchiNET/ASF-ui#888]
## Description
I switched from running ASF in a screen instance to a Docker with the IPC+UI. I've setup a bot but it can't start because it cannot login without the 2FA code.

Am I doing something wrong here or isn't this supported? Is there a workaround?

## Steps to reproduce
- Use the UI to create a bot with name, Steam username & Steam password
- Start newly created bot

## Expected behavior
The UI should ask for me to enter a 2FA code, similair to the 'oldschool' command line.

## Current behavior
Nothing is asked and the UI gives an error, the bot is stopped.

## Additional information

Using Docker w/ Portainer. Config folder mapped to folder on the host.

### Full log

```
[21:45:18] INFO ASF > Start() IPC server ready!
[21:45:19] INFO Bot1 > Start() Starting...
[21:45:19] INFO Bot1 > Connect() Connecting...
[21:45:20] INFO Bot1 > OnConnected() Connected to Steam!
[21:45:20] INFO Bot1 > OnConnected() Logging in...
[21:45:21] INFO Bot1 > Stop() Stopping...
```

### IPC.config
```json
{
	"Kestrel": {
		"Endpoints": {
			"HTTP": {
				"Url": "http://*:1242"
			}
		}
	}
}
```

**Comment by MrBurrBurr** [comment]
Hey,

I wouldnt call it a bug but a missing *feature. As for now I would recommend following the [wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker#pro-tips) and use the `input` command.

*Out of the blue I am not even sure what we can do about it. When I got more time I will look into it.

**Comment by MrBurrBurr** [comment]
So far I don't see any good way to implement this feature since we are missing information from ASF side. Any ideas @JustArchi?

**Comment by JustArchi** [comment]
@MrBurrBurr There are "hacky" ways to do that (using log parsing and `input` command), but it's a good time to do it in the proper way instead. I think that `Bot` could expose required input type, and ASF-ui could check for that (since it already updates bots in a loop). Once it detects that a bot requires input, you could use a new API endpoint that I'll make which would allow you to put it (like in input command), then ask user if he wants to start the bot again.

This should work only in `Headless` mode, as it doesn't make any sense otherwise - ASF will wait for user input and won't cancel it once started, regardless what happens afterwards. The user asking for this feature is probably already using one (guessing from his "stopping" message), but I'm pointing it out anyway.

Let me know what you think of that idea, if you're willing to code it, I can implement the above in ASF core.

**Comment by MrBurrBurr** [comment]
Sounds good to me, I'll do my best to implement it but I can't say how long it will take.
